apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: buymore
        image: aniediogo/buymore:1.1
        ports:
        - containerPort: 8000

---


apiVersion: v1
kind: Service
metadata:
  name: nodeserv
spec:
  selector:
    app: myapp
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 80
    nodePort: 30000
  type: NodePort
